jobqueueconfig:
	schedulerMap:
		ERPTASK:
			id: ERPTASK
			threadCount: 8
		REPORT:
			id: REPORT
			threadCount: 2
	jobtype:
		ERP:
			id: ERP
			msrID: ERP
			name: ERP
			executorclassName: dyna.app.service.brs.erpi.ERPIJob.ERPIJob
			schedulerID: ERPTASK
			timeOut: 30
		CFERP:
			id: CFERP
			msrID: CFERP
			name: CFERP
			executorclassName: dyna.app.service.brs.erpi.ERPIJob.CFERPIJob
			schedulerID: ERPTASK
			timeOut: 30
		ERPpriority:
			id: ERPpriority
			msrID: ERPpriority
			name: ERPpriority
			executorclassName: dyna.app.service.brs.erpi.ERPIJob.ERPpriorityJob
			schedulerID: ERPTASK
			priority: 1
			timeOut: 30
		BOM:
			id: BOM
			msrID: BOM
			name: BOM
			executorclassName: dyna.app.service.brs.srs.job.BOMReportJob
			schedulerID: REPORT
			timeOut: 30
		PreSearch:
			id: PreSearch
			msrID: PreSearch
			name: PreSearch
			executorclassName: dyna.app.service.brs.srs.job.PreSearchRepeortJob
			schedulerID: REPORT
			timeOut: 30
		Summary:
			id: Summary
			msrID: Summary
			name: Summary
			executorclassName: dyna.app.service.brs.srs.job.SummaryReportJob
			schedulerID: REPORT
			timeOut: 30
		FoundationReport:
			id: FoundationReport
			msrID: FoundationReport
			name: FoundationReport
			executorclassName: dyna.app.service.brs.srs.job.GenericReportJob
			schedulerID: REPORT
			timeOut: 30
		ECReport:
			id: ECReport
			msrID: ECReport
			name: ECReport
			executorclassName: dyna.app.service.brs.srs.job.ECReportJob
			schedulerID: REPORT
			timeOut: 30
		AdvancedSearch:
			id: AdvancedSearch
			msrID: AdvancedSearch
			name: AdvancedSearch
			executorclassName: dyna.app.service.brs.srs.job.AdvancedSearchJob
			schedulerID: REPORT
			timeOut: 30
		ConfigBOMReport:
			id: ConfigBOMReport
			msrID: ConfigBOMReport
			name: ConfigBOMReport
			executorclassName: dyna.app.service.brs.srs.job.ConfigBOMRepeortJob
			schedulerID: REPORT
			timeOut: 30
		JobPolling:
			id: JobPolling
			msrID: JobPolling
			name: JobPolling
			executorclassName: dyna.app.service.das.jss.ScheduledTaskJobPollingImpl
			schedulerID: timerScheduler
			timeOut: 30
			cron: "0/30 * * * * *"
		JobGetERPStaus:
			id: JobGetERPStaus
			msrID: JobGetERPStaus
			name: JobGetERPStaus
			executorclassName: dyna.app.service.das.jss.ScheduledTaskJobGetERPStausImpl
			schedulerID: timerScheduler
			timeOut: 30
			cron: "* 0/2 * * * *"
		TaskDeleteJob:
			id: TaskDeleteJob
			msrID: TaskDeleteJob
			name: TaskDeleteJob
			executorclassName: dyna.app.service.das.jss.ScheduledTaskDeleteJobImpl
			schedulerID: timerScheduler
			timeOut: 30
			cron: "* * 2 * * *"
